name: agency31_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0-271.7.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  get: ^4.6.5
  shared_preferences: ^2.0.15
  http: ^0.13.4
  google_fonts: ^3.0.1
  flutter_screenutil: ^5.5.4
  path_provider: ^2.0.11
  carousel_slider: ^4.1.1
  cached_network_image: ^3.2.0
  shimmer: ^2.0.0
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  firebase_auth: ^4.0.1
  firebase_core: ^2.0.0
  google_sign_in: ^5.4.2
  cloud_firestore: ^4.0.1
  firebase_messaging: ^14.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # fonts:
  #   - family: Raleway
  #     fonts:
  #       - asset: assets/fonts/Raleway-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
